AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  doAnswer

  Sample SAM Template for doAnswer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CardsFn:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: cards.doAnswer
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/doAnswer
            Method: post
  CardsBucket:
    Type: AWS::S3::Bucket
  CardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: rand
          AttributeType: N
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: cards-rand
          KeySchema:
            - AttributeName: rand
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
  AnswersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "user_uuid"
          AttributeType: "S"
        - AttributeName: "card_uuid"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_uuid"
          KeyType: "HASH"
        - AttributeName: "card_uuid"
          KeyType: "RANGE"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CardsFnApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CardsFn:
    Value: !GetAtt CardsFn.Arn
  CardsFnIamRole:
    Value: !GetAtt CardsFnRole.Arn
  CardsBucketName:
    Value: !Ref CardsBucket
  CardsTableName:
    Value: !Ref CardsTable
